Update Jenkinsfile1
changes in Dependencies

diff --git a/Jenkinsfile1 b/Jenkinsfile1
--- a/Jenkinsfile1
+++ b/Jenkinsfile1
@@ -52,6 +52,20 @@ pipeline {
                 '''
             }
         }
+        steps {
+                sh '''
+                cd elearning-mern-platform-app/backend
+                ls -la  # Verify package.json exists
+                if [ -f package.json ]; then
+                    rm -rf node_modules package-lock.json  # Remove old dependencies
+                    npm install  # Install fresh dependencies
+                else
+                    echo "Error: package.json not found in elearning-mern-platform-app/backend!"
+                    exit 1
+                fi
+                '''
+            }
+        }
         stage('OWASP FS Scan') {
             steps {
                 dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
